name: Update README

on:
  schedule:
    - cron: "15 6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: |
          python update_readme.py

      - name: Commit changes
        run: |
          git config user.name "LeetCode Bot"
          git config user.email "leetcode-bot@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📄 Update README with latest problems"
          git push
