name: Sync LeetCode to GitHub

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6:00 AM UTC
  workflow_dispatch:    

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        run: python leetcode_sync.py

      - name: Commit and push changes
        run: |
          git config user.name "LeetCode Bot"
          git config user.email "leetcode-bot@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Sync LeetCode submissions"
          git push
