name: Sync LeetCode to GitHub

on:
  schedule:
    - cron: "0 6 * * *"  # every day at 6:00 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: python sync.py

      - name: Commit and push changes
        run: |
          git config --global user.name "LeetCode Bot"
          git config --global user.email "leetcode-bot@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync LeetCode submissions"
          git push

